version: '3'

services:
  database:
    image: 'postgres:14.1'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: quarkus_user
      POSTGRES_PASSWORD: quarkus_pass
      POSTGRES_DB: quarkus_test
    volumes:
      - postgres:/var/lib/postgresql/data

  database_ui:
    image: dpage/pgadmin4:6.21
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: quarkus_pass
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database

  tracing:
    image: 'jaegertracing/all-in-one:latest'
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268

volumes:
  postgres:
  pgadmin: